name: sass_builder_example
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: nshahan <email@example.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  sass_builder: ^0.0.1

dependency_overrides:
  sass_builder:
    path: ../

transformers:
- sass_builder
