name: sass_builder
description: A Builder to compile .css files from .scss sources using the Dart
  implementation of Sass.
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0-dev.infinity'

dependencies:
  barback: ^0.15.2
  build: ^0.10.0
  build_barback: ^0.4.0
  package_resolver: ^1.0.2
  path: ^1.4.2
  sass: ^1.0.0-beta.2

dev_dependencies:
  test: ^0.12.0
